
import java.awt.Component;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author aakash
 */
public class MakeAppoinment extends javax.swing.JFrame {

    /**
     * Creates new form MakeAppoinment
     */
    int flag = 1;
    int z;

    public MakeAppoinment() {
        initComponents();
    }
    AppointmentMgr test = new AppointmentMgr();
    LoginMgr tr=new LoginMgr();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 107, 255));

        jLabel1.setText("Type Of Doctor");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select", "General Physician", "Dentist", "ENT Specialist", "Gynecologist", "Pediatricians", "Dermatologists" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Name Of Doctor");

        jButton2.setBackground(new java.awt.Color(51, 204, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Upload Medical Reports");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Select Date");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Slot" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Date", "Today" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel3.setText("Time Slots");

        jLabel4.setText("Date");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select Type" }));
        jComboBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox4ItemStateChanged(evt);
            }
        });

        jButton1.setText("<--");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jButton1)
                .addGap(244, 244, 244)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //if (this.jTextField2.getText().equals("1")||this.jTextField2.getText().equals("@")||this.jTextField2.getText().equals("4")||this.jTextField2.getText().equals("2"))
        //{
        //this.jLabel5.setText("ERROR NO DOCTOR FOUND");
        //}
        //else
        //{
        DisplayMgr.showUpldMedRecFrmMakeAppt();
        //new MakeAppoinment().setVisible(false);
        
        //}// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /*   private void ll(){
         String path ="/home/aakash/Downloads/MidTerm2/src/booked_slots.txt";
         String line="";
        try {
            BufferedReader br = new BufferedReader(new FileReader(path));
            while((line= br.readLine()) != null){
                System.out.println(line);
            }
            
            // TODO add your handling code here:
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MakeAppoinment.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MakeAppoinment.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
    
}*/
    public int slotChecker() {

        String path = "booked_slots.txt";
        String line = "";
        try {
            BufferedReader br = new BufferedReader(new FileReader(path));
            String value = jComboBox2.getSelectedItem().toString();
            System.out.println(value);
            //test.slotChecker("08:00-8:15", "ad65");
            while ((line = br.readLine()) != null) {
                //System.out.println(line);
                //int d = jComboBox2.getSelectedIndex();
                //String value= jComboBox2.getSelectedItem().toString();
                //line=line.toString();
                System.out.println(line);
                String[] values = line.split(";");
                String id = values[0];
                String slot1 = values[1];

                //if (line == null ? value == null : line.equals(value))
                if (slot1 == null ? value == null : slot1.equals(value)) {

                    System.out.println("Booked");
                    jLabel6.setText("Slot is Already Booked.Check for Another Slot");
                    flag = 0;
                    break;

                } else {

                    jLabel6.setText("Slot is Available");
                    flag = 1;

                }
            }

            // TODO add your handling code here:
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MakeAppoinment.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MakeAppoinment.class.getName()).log(Level.SEVERE, null, ex);
        }
        return flag;

    }

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed

        if (jComboBox2.getSelectedItem() != null) {

            z = slotChecker();
            System.out.println(z);
        }

        /*String path ="/home/aakash/Downloads/MidTerm2/src/booked_slots.txt";
         String line="";
        try {
            BufferedReader br = new BufferedReader(new FileReader(path));
            String value= jComboBox2.getSelectedItem().toString();
            System.out.println(value);
            //test.slotChecker("08:00-8:15", "ad65");
            while((line= br.readLine()) != null){
                //System.out.println(line);
                //int d = jComboBox2.getSelectedIndex();
                //String value= jComboBox2.getSelectedItem().toString();
                //line=line.toString();
                System.out.println(line);
                String[] values =  line.split(";");
                String id=values[0];
                String slot1=values[1];
                
                //if (line == null ? value == null : line.equals(value))
                if (slot1 == null ? value == null : slot1.equals(value)){
                    
                    System.out.println("Booked");
                    jLabel6.setText("Slot is Already Booked.Check for Another Slot");
                    flag=0;
                    break;
                
                    
                    
                    
                    
                }
                else{
                    
                    jLabel6.setText("Slot is Available");
                    flag=1;
                    
                }
            }
            
            // TODO add your handling code here:
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MakeAppoinment.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MakeAppoinment.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String wrt = jComboBox2.getSelectedItem().toString();
        String name1 = jComboBox4.getSelectedItem().toString();
        String id1 = test.searchByName(name1);
        String patid1=tr.LogPat1();
        /*try {
            // TODO add your handling code here:
            FileWriter Writer= new FileWriter("/home/aakash/Downloads/MidTerm2/src/booked_slots.txt",true);
            Writer.write(""+"11");
            Writer.write(System.getProperty("line.seperator"));
            Writer.close();
            JOptionPanel.showMassageDialog(null,"Success");
            setVisible(false);
            new InsertData().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(MakeAppoinment.class.getName()).log(Level.SEVERE, null, ex);
        }*/
 /*BufferedWriter writer = null;
    try {
        writer = new BufferedWriter(new FileWriter("/home/aakash/Downloads/MidTerm2/src/booked_slots.txt"));
        
        writer.write(""+wrt);
    } catch (IOException e) {
        System.err.println(e);
    } finally {
        if (writer != null) {
            try {
                writer.close();
            } catch (IOException e) {
                System.err.println(e);
            }
        }
    }*/
        int v = jComboBox1.getSelectedIndex();
        int u = jComboBox3.getSelectedIndex();

        if (z == 0 || v == 0 || u==0) {

            Component fr = null;

            JOptionPane.showMessageDialog(fr,
                    "Improper Selction! Select Again");

        } else {

            //test.saveInfo(wrt,id1);
            test.saveInfo2(wrt,id1,patid1);

            Component frame = null;

            JOptionPane.showMessageDialog(frame,
                    "Appointment "+"at " + wrt + " for " + name1 + " booked");
        }
        //System.out.println(flag);
        //test.saveInfo(wrt, "b");
        /*if (flag==0 || v==0){
        
            Component fr = null;

    JOptionPane.showMessageDialog(fr,
    "Choose another date");
        
    }
    else{
        
        try (FileWriter f = new FileWriter("/home/aakash/Downloads/MidTerm2/src/booked_slots.txt", true); 
            BufferedWriter b = new BufferedWriter(f); 
            PrintWriter p = new PrintWriter(b);){

    
    
        p.print(""); 
        p.println(wrt);
    
    //p.close();
            Component frame = null;

        JOptionPane.showMessageDialog(frame,
        "Appointment Date Booked");
    //p.println("Bori"); 
        } catch (IOException i) { 
            i.printStackTrace(); }
    }
    
   /* try (FileWriter f = new FileWriter("/home/aakash/Downloads/MidTerm2/src/booked_slots.txt", true); 
        BufferedWriter b = new BufferedWriter(f); 
        PrintWriter p = new PrintWriter(b);){

    
    
    p.print(""); 
    p.println(wrt);
    
    //p.close();
            Component frame = null;

    JOptionPane.showMessageDialog(frame,
    "Appointment Date Booked");
    //p.println("Bori"); 
    } catch (IOException i) { 
        i.printStackTrace(); }*/


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        ArrayList<String> array = test.returnDocName("General Physician");
        Iterator<String> iter;
        ArrayList<String> array2 = test.returnDocName("Dentist");
        Iterator<String> iter2;
        ArrayList<String> array3 = test.returnDocName("ENT Specialist");
        Iterator<String> iter3;
        ArrayList<String> array4 = test.returnDocName("Gynecologist");
        Iterator<String> iter4;
        ArrayList<String> array5 = test.returnDocName("Pediatricians");
        Iterator<String> iter5; 
        ArrayList<String> array6 = test.returnDocName("Dermatologists");
        Iterator<String> iter6;       
        if (jComboBox1.getSelectedItem().equals("General Physician")) {
            //jComboBox4.removeAllItems();
            for(int i=jComboBox4.getItemCount()-1;i>0;i--){
                jComboBox4.removeItemAt(i);
            }
            //jComboBox4.addItem("1");
            //array.add("Dr. Abhinibesh Chatterjee");
            //array.add("Dr. Ansheswa Paul");
            //array.add("GAS");
            iter = array.iterator();
            while (iter.hasNext()) {
                jComboBox4.addItem(iter.next());
                //String ide = iter.next();
                /*ArrayList<String> slot = test.returnDocSlots(iter.next());
                Iterator<String> iter_sl;
                iter_sl = slot.iterator();
                jComboBox2.removeAllItems();
                while (iter_sl.hasNext()) {
                    jComboBox2.addItem(iter_sl.next());
                }*/
            }
            jComboBox4.removeItemAt(0);
            
         

            
        } else if (jComboBox1.getSelectedItem().equals("Dentist")) {
            //jComboBox4.removeAllItems();
            for(int i=jComboBox4.getItemCount()-1;i>0;i--){
                jComboBox4.removeItemAt(i);
            }
            //array.add("Dr. Shruti Sen");
            //array.add("Dr. Prabash Ghosh");
            //array.add("GA");
            iter2 = array2.iterator();
            while (iter2.hasNext()) {
                jComboBox4.addItem(iter2.next());
            }
            jComboBox4.removeItemAt(0);
            
            
            
            /*String temp = jComboBox4.getSelectedItem().toString();
            String ide = test.searchByName(temp);
            System.out.println(jComboBox4.getSelectedItem());
            Object n = jComboBox4.getSelectedItem();
            if (jComboBox4.getSelectedItem().equals("Vijay Kumar")) {
                System.out.println(114);

                ArrayList<String> slot = test.returnDocSlots(ide);
                Iterator<String> iter_sl;
                iter_sl = slot.iterator();
                jComboBox2.removeAllItems();
                while (iter_sl.hasNext()) {
                    jComboBox2.addItem(iter_sl.next());
                }
            }
            else{
                
                jComboBox2.removeAllItems();
                jComboBox2.addItem("1235");
            }*/

        } else if (jComboBox1.getSelectedItem().equals("ENT Specialist")) {
            //jComboBox4.removeAllItems();
            //array.add("Dr. Jacob Mall");
            //array.add("Dr. Jarad Sen");
            //array.add("GA");
            for(int i=jComboBox4.getItemCount()-1;i>0;i--){
                jComboBox4.removeItemAt(i);
            }
            iter3 = array3.iterator();
            while (iter3.hasNext()) {
                jComboBox4.addItem(iter3.next());
            }
           jComboBox4.removeItemAt(0); 
           
           
        } else if (jComboBox1.getSelectedItem().equals("Gynecologist")) {
            //jComboBox4.removeAllItems();
            for(int i=jComboBox4.getItemCount()-1;i>0;i--){
                jComboBox4.removeItemAt(i);
            }
            //array.add("Dr. Riya Mall");
            //array.add("Dr. Kinsuk Gupta");
            //array.add("GA");
            iter4 = array4.iterator();
            while (iter4.hasNext()) {
                jComboBox4.addItem(iter4.next());
            }
            jComboBox4.removeItemAt(0); 
            
        } else if (jComboBox1.getSelectedItem().equals("Pediatricians")) {
            //jComboBox4.removeAllItems();
            for(int i=jComboBox4.getItemCount()-1;i>0;i--){
                jComboBox4.removeItemAt(i);
            }
            //array.add("Dr. Ashis Das");
            //array.add("Dr. Lalu Kumar");
            //array.add("GA");
            iter5 = array5.iterator();
            while (iter5.hasNext()) {
                jComboBox4.addItem(iter5.next());
            }
            jComboBox4.removeItemAt(0); 
            
        } else if (jComboBox1.getSelectedItem().equals("Dermatologists")) {
            //jComboBox4.removeAllItems();
            for(int i=jComboBox4.getItemCount()-1;i>0;i--){
                jComboBox4.removeItemAt(i);
            }
            //array.add("Dr. Umesh Mall");
            //array.add("Dr. Rishav Patel");
            //array.add("Dr. Yamini Kapoor");
            iter6 = array6.iterator();
            while (iter6.hasNext()) {
                jComboBox4.addItem(iter6.next());
            }
            jComboBox4.removeItemAt(0); 
            
        } else {
            //jComboBox4.removeAllItems();
            for(int i=jComboBox4.getItemCount()-1;i>0;i--){
                jComboBox4.removeItemAt(i);
            }
            //boolean add = array.add(new DoctorEntity("Please Select Type"));
            //array.add("Please Select Type");
            //iter=array.iterator();
            //while(iter.hasNext()){
            jComboBox4.addItem("Please Select Type");
            jComboBox4.removeItemAt(0); 
            //}

        }


    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox4ItemStateChanged
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem().equals("General Physician")){
            ArrayList<String> array = test.returnDocName("General Physician");
            Iterator<String> iter;
            iter = array.iterator();
            String a1 = array.get(0);
            String a2 = array.get(1);
            
            

            
                if (jComboBox4.getSelectedItem().equals(a1)) {
                    System.out.println(114);
                    String ide = test.searchByName(a1);

                    ArrayList<String> slot = test.returnDocSlots(ide);
                    Iterator<String> iter_sl;
                    iter_sl = slot.iterator();
                    jComboBox2.removeAllItems();
                    while (iter_sl.hasNext()) {
                        jComboBox2.addItem(iter_sl.next());
                    }
                }
               
                else {
                    System.out.println(113);
                  
                    String ide = test.searchByName(a2);

                    ArrayList<String> slot = test.returnDocSlots(ide);
                    Iterator<String> iter_sl;
                    iter_sl = slot.iterator();
                    jComboBox2.removeAllItems();
                    while (iter_sl.hasNext()) {
                        jComboBox2.addItem(iter_sl.next());
                    } 
            }

        
        }
        
        else if(jComboBox1.getSelectedItem().equals("Dentist")){
            ArrayList<String> array = test.returnDocName("Dentist");
            Iterator<String> iter;
            iter = array.iterator();
            String a1 = array.get(0);
            String a2 = array.get(1);
            
            

                if (jComboBox4.getSelectedItem().equals(a1)) {
                    System.out.println(114);
                    String ide = test.searchByName(a1);

                    ArrayList<String> slot = test.returnDocSlots(ide);
                    Iterator<String> iter_sl;
                    iter_sl = slot.iterator();
                    jComboBox2.removeAllItems();
                    while (iter_sl.hasNext()) {
                        jComboBox2.addItem(iter_sl.next());
                    }
                }
               
                else {
                    System.out.println(113);
                  
                    String ide = test.searchByName(a2);

                    ArrayList<String> slot = test.returnDocSlots(ide);
                    Iterator<String> iter_sl;
                    iter_sl = slot.iterator();
                    jComboBox2.removeAllItems();
                    while (iter_sl.hasNext()) {
                        jComboBox2.addItem(iter_sl.next());
                    } 
            }
        }
        
         else if(jComboBox1.getSelectedItem().equals("ENT Specialist")){
            ArrayList<String> array = test.returnDocName("ENT Specialist");
            Iterator<String> iter;
            iter = array.iterator();
            String a1 = array.get(0);
            //String a2 = array.get(1);
            

            
                if (jComboBox4.getSelectedItem().equals(a1)) {
                    System.out.println(114);
                    String ide = test.searchByName(a1);

                    ArrayList<String> slot = test.returnDocSlots(ide);
                    Iterator<String> iter_sl;
                    iter_sl = slot.iterator();
                    jComboBox2.removeAllItems();
                    while (iter_sl.hasNext()) {
                        jComboBox2.addItem(iter_sl.next());
                    }
                }
 
 

        }
         
          else if(jComboBox1.getSelectedItem().equals("Gynecologist")){
            ArrayList<String> array = test.returnDocName("Gynecologist");
            Iterator<String> iter;
            iter = array.iterator();
            String a1 = array.get(0);
            //String a2 = array.get(1);

            
                if (jComboBox4.getSelectedItem().equals(a1)) {
                    System.out.println(114);
                    String ide = test.searchByName(a1);

                    ArrayList<String> slot = test.returnDocSlots(ide);
                    Iterator<String> iter_sl;
                    iter_sl = slot.iterator();
                    jComboBox2.removeAllItems();
                    while (iter_sl.hasNext()) {
                        jComboBox2.addItem(iter_sl.next());
                    }
                }
               

        } 
          
          
         else if(jComboBox1.getSelectedItem().equals("Pediatricians")){
            ArrayList<String> array = test.returnDocName("Pediatricians");
            Iterator<String> iter;
            iter = array.iterator();
            String a1 = array.get(0);
            String a2 = array.get(1);
            
            

            
                if (jComboBox4.getSelectedItem().equals(a1)) {
                    System.out.println(114);
                    String ide = test.searchByName(a1);

                    ArrayList<String> slot = test.returnDocSlots(ide);
                    Iterator<String> iter_sl;
                    iter_sl = slot.iterator();
                    jComboBox2.removeAllItems();
                    while (iter_sl.hasNext()) {
                        jComboBox2.addItem(iter_sl.next());
                    }
                }
               
                else {
                    System.out.println(113);
                  
                    String ide = test.searchByName(a2);

                    ArrayList<String> slot = test.returnDocSlots(ide);
                    Iterator<String> iter_sl;
                    iter_sl = slot.iterator();
                    jComboBox2.removeAllItems();
                    while (iter_sl.hasNext()) {
                        jComboBox2.addItem(iter_sl.next());
                    } 
            }

        
        }
     
        else if(jComboBox1.getSelectedItem().equals("Dermatologists")){
            ArrayList<String> array = test.returnDocName("Dermatologists");
            Iterator<String> iter;
            iter = array.iterator();
            String a1 = array.get(0);
            String a2 = array.get(1);
            

            
            
                if (jComboBox4.getSelectedItem().equals(a1)) {
                    System.out.println(114);
                    String ide = test.searchByName(a1);

                    ArrayList<String> slot = test.returnDocSlots(ide);
                    Iterator<String> iter_sl;
                    iter_sl = slot.iterator();
                    jComboBox2.removeAllItems();
                    while (iter_sl.hasNext()) {
                        jComboBox2.addItem(iter_sl.next());
                    }
                }
               
                else {
                    System.out.println(113);
                  
                    String ide = test.searchByName(a2);

                    ArrayList<String> slot = test.returnDocSlots(ide);
                    Iterator<String> iter_sl;
                    iter_sl = slot.iterator();
                    jComboBox2.removeAllItems();
                    while (iter_sl.hasNext()) {
                        jComboBox2.addItem(iter_sl.next());
                    } 
            }

        
        }
        else{
            
            jComboBox2.removeAllItems();
            jComboBox2.addItem("Select Slots");
        }
         


        /*if (jComboBox4.getSelectedItem()!= null && jComboBox4.getSelectedItem().equals("Vijay Kumar")){
            
            jComboBox2.removeAllItems();
            jComboBox2.addItem("Please Select Type");
            
        }
        else{
            
            
        }*/
       
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox4ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DisplayMgr.showMakeApptToPatInterface();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakeAppoinment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakeAppoinment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakeAppoinment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakeAppoinment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakeAppoinment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
